import { CMSTask, CMSProject } from '../../shared/types';
import { Slug } from './Slug';

/**
 * VelocityGenerator - Decomplected artifact creation engine.
 * Mimics PubliiEx.Generator patterns for high-fidelity content delivery.
 */
export class VelocityGenerator {
    /**
     * Generates a structured report from a task.
     * @param task - The completed research task
     * @param project - The parent project context
     * @returns Formatted Markdown/HTML string
     */
    static generateReport(task: CMSTask, project: CMSProject): string {
        const title = task.title.toUpperCase();
        const slug = Slug.generatePath(task.title, task.id);
        const dateStr = new Date(task.updatedAt).toLocaleDateString('en-GB', {
            day: 'numeric',
            month: 'long',
            year: 'numeric'
        });

        const theme = this.selectTheme(task);

        return theme.render({
            title,
            date: dateStr,
            projectName: project.name,
            content: task.output || '',
            tokens: task.tokenUsage
        });
    }

    private static selectTheme(task: CMSTask) {
        if (task.title.includes('$') || task.title.toLowerCase().includes('analysis')) {
            return StrategicTheme;
        }
        return DefaultTheme;
    }
}

/**
 * Theme Interface for Layout Modules
 */
interface ThemeLayout {
    render(data: {
        title: string;
        date: string;
        projectName: string;
        content: string;
        tokens?: { input: number; output: number };
    }): string;
}

const DefaultTheme: ThemeLayout = {
    render({ title, date, projectName, content, tokens }) {
        return `
# ${title}
> Generated for **${projectName}** on ${date}

---

<article data-pagefind-body>
${content}
</article>

---
*Generated by Gemini Ops | ${tokens ? `Tokens: ${tokens.input} in / ${tokens.output} out` : 'Edge Native'}*
`.trim();
    }
};

const StrategicTheme: ThemeLayout = {
    render({ title, date, projectName, content, tokens }) {
        // Simple heuristic to get first paragraph or specific section
        const extractSummary = (text: string): string => {
            const lines = text.split('\n').filter(l => l.trim().length > 0);
            return lines[0] || 'Strategic insights compiled from edge research.';
        };

        // High-fidelity layout for analytical tasks
        return `
# 📊 STRATEGIC ANALYSIS: ${title}
## Project: ${projectName} | ${date}

---

### 🔍 Executive Summary
<div data-pagefind-meta="summary">
${extractSummary(content)}
</div>

### 🛠 Evidence & Analysis
<article data-pagefind-body>
${content}
</article>

---
### 🛠 Metadata
- **Engine**: Gemini 3.0 Pro
- **Timestamp**: ${new Date().toISOString()}
- **Consumption**: ${tokens ? `${tokens.input + tokens.output} total tokens` : 'Standard API'}

> **Confidentiality Notice**: This report is intended for internal operations of ${projectName}.
`.trim();
    }
};
